import streamlit as st

st.title("topics")
st.header("machine learning")
st.subheader("part1")
st.info("info")
st.warning("warning")
st.success("success")
st.error("error")
st.write(":moon:")
st.write(":family:")
st.text("hello everyone")
st.caption("welcome")
st.checkbox("login")
st.button("click")
st.selectbox("pick course",["ML","cloud","CS"])
st.radio("pick your gender",["male","female","other"])
st.multiselect("pick course",["ML","cloud","CS"])
